import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { cookies } from "next/headers";
import { jwtDecode } from "jwt-decode";

 
export async function generateMetadata () { 
  const cookiesStore = await cookies();
  const adminToken  = cookiesStore.get("adminToken")?.value;
  const userToken  = cookiesStore.get("userToken")?.value;
  let role = "User";
  try {
    if(adminToken){
      const decoded: any = jwtDecode(adminToken);
      if(decoded.role=== 'admin') role = "Admin";
    } else if(userToken){
      const decode: any = jwtDecode(userToken);
      if(decode.role === 'user') role = "User";
    }
  }catch {}
  return {
    title: `Dashboard | Shipquickr - ${role} & Dashboard`,
    description: "Generated by create next app",
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer position="top-right" autoClose={3000} />

      </body>
    </html>
  );
}
